TextTasks/Models/ErrorViewModel.cs
using System;

namespace TextTasks.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

TextTasks/Models/Task.cs
using System;

namespace TextTasks.Models
{
	public class Task
	{
		public int TaskId { get; set; }
		public string Text { get; set; }
		public DateTime? Completed { get; set; }
	}
}

TextTasks/Models/TaskIdentifier.cs
using System;

namespace TextTasks.Models
{
	public class TaskIdentifier
	{
		public int TaskId { get; set; }
	}
}

TextTasks/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TextTasks.Models;

using MySql.Data.MySqlClient;
using dto = TextTasks.Models;

using Microsoft.AspNetCore.Authorization;


namespace TextTasks.Controllers
{
	[Authorize]
	public class HomeController : Controller
	{
		private MySqlDatabase MySqlDatabase { get; set; }
		public HomeController(MySqlDatabase mySqlDatabase)
		{
			this.MySqlDatabase = mySqlDatabase;
		}

		public async Task<IActionResult> Index()
		{
			return View(await this.GetTasks());
		}
		private async Task<List<dto.Task>> GetTasks()
		{
			var ret = new List<dto.Task>();

			var cmd = this.MySqlDatabase.Connection.CreateCommand() as MySqlCommand;
			cmd.CommandText = @"SELECT TaskId, Text, Completed FROM Tasks WHERE Archived IS NULL";

			using (var reader = await cmd.ExecuteReaderAsync())
				while (await reader.ReadAsync())
				{
					var t = new dto.Task()
					{
						TaskId = reader.GetFieldValue<int>(0),
						Text = reader.GetFieldValue<string>(1)
					};
					if (!reader.IsDBNull(2))
						t.Completed = reader.GetFieldValue<DateTime>(2);

					ret.Add(t);
				}
			return ret;
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

TextTasks/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using MySql.Data.MySqlClient;

using dto = TextTasks.Models;

using Microsoft.AspNetCore.Authorization;

namespace TextTasks.Controllers
{
	[Authorize]
	public class TasksController : Controller
	{
		private MySqlDatabase MySqlDatabase { get; set; }
		public TasksController(MySqlDatabase mySqlDatabase)
		{
			this.MySqlDatabase = mySqlDatabase;
		}

		[HttpPost]
		public void Complete(dto.TaskIdentifier input)
		{
			var cmd = this.MySqlDatabase.Connection.CreateCommand() as MySqlCommand;
			cmd.CommandText = @"UPDATE Tasks SET Completed = STR_TO_DATE(@Date, '%Y/%m/%d') WHERE TaskId = @TaskId;";
			cmd.Parameters.AddWithValue("@TaskId", input.TaskId);
			cmd.Parameters.AddWithValue("@Date", DateTime.Now.ToString("yyyy/MM/dd"));

			var recs = cmd.ExecuteNonQuery();
		}
		[HttpPost]
		public void Incomplete(dto.TaskIdentifier input)
		{
			var cmd = this.MySqlDatabase.Connection.CreateCommand() as MySqlCommand;
			cmd.CommandText = @"UPDATE Tasks SET Completed = NULL WHERE TaskId = @TaskId;";
			cmd.Parameters.AddWithValue("@TaskId", input.TaskId);

			var recs = cmd.ExecuteNonQuery();
		}
		[HttpPost]
		public void Archive(dto.TaskIdentifier input)
		{
			var cmd = this.MySqlDatabase.Connection.CreateCommand() as MySqlCommand;
			cmd.CommandText = @"UPDATE Tasks SET Archived = STR_TO_DATE(@Date, '%Y/%m/%d') WHERE TaskId = @TaskId;";
			cmd.Parameters.AddWithValue("@TaskId", input.TaskId);
			cmd.Parameters.AddWithValue("@Date", DateTime.Now.ToString("yyyy/MM/dd"));

			var recs = cmd.ExecuteNonQuery();
		}

		[HttpPost]
		public string Sms()
		{
			var input = Request.Form["Body"];
			string response = null;

			var cmd = this.MySqlDatabase.Connection.CreateCommand() as MySqlCommand;
			cmd.CommandText = @"INSERT INTO Tasks(Text,Created) VALUES (@Text,STR_TO_DATE(@Date, '%Y/%m/%d'));";
			cmd.Parameters.AddWithValue("@Text", input);
			cmd.Parameters.AddWithValue("@Date", DateTime.Now.ToString("yyyy/MM/dd"));

			var recs = cmd.ExecuteNonQuery();

			if (recs == 1)
				response = "OK";
			else
				response = "Sorry! I didn't get that.";

			return response;
		}
	}
}

TextTasks/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<script>
    function Click(id, action) {
        if(action !== "Archive" || confirm('Are you sure you want to archive this task?'))
            $.ajax({
                url: ('@Url.Action("REPLACE", "Tasks")'.replace('REPLACE', action)),
                type: 'POST',
                data: { TaskId: id }
            }).done(function ()
            {
                if (action === 'Archive')
                    document.getElementById('tr_' + id).style.display = "none";
                else if (action === 'Complete')
                {
                    document.getElementById('td_complete_' + id).style.display = "";
                    document.getElementById('td_incomplete_' + id).style.display = "none";
                }
                else if (action === 'Incomplete')
                {
                    document.getElementById('td_complete_' + id).style.display = "none";
                    document.getElementById('td_incomplete_' + id).style.display = "";
                }
            });
    }
</script>

<div class="row">
    <!-- List of Tasks -->
    <h2>Tasks</h2>
    <table>
        <tr class="header">
            <td class="empty"></td>
            <td class="empty"></td>
            <td>Description</td>
        </tr>
        @if (Model != null)
        {
            var added = false;
            foreach (var t in Model)
            {
                <tr id="tr_@t.TaskId">
                    <td><i class="fas fa-archive" onclick="Click(@t.TaskId,'Archive')"></i></td>
                    <td id="td_incomplete_@t.TaskId" style="display:@(t.Completed == null ? "" : "none");"><i class="far fa-square" onclick="Click(@t.TaskId,'Complete')"></i></td>
                    <td id="td_complete_@t.TaskId" style="display:@(t.Completed == null ? "none" : "");"><i class="far fa-check-square" onclick="Click(@t.TaskId,'Incomplete')"></i></td>
                    <td>@t.Text</td>
                </tr>

                added = true;
            }

            if (!added)
            {
                <tr>
                    <td></td>
                    <td></td>
                    <td style="display:none;"></td>
                    <td>No tasks found.</td>
                </tr>
            }
        }
    </table>
</div>

TextTasks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TextTasks</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TextTasks</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - TextTasks - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>